/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as LoginRouteImport } from './routes/login.route'
import { Route as DashboardIndexImport } from './routes/_dashboard/index'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/_dashboard/tasks.$taskId.route'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const LoginRouteRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTasksTaskIdRouteRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/tasks/$taskId': {
      id: '/_dashboard/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTasksTaskIdRouteRoute: typeof DashboardTasksTaskIdRouteRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTasksTaskIdRouteRoute: DashboardTasksTaskIdRouteRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRoute
  '': typeof DashboardRouteWithChildren
  '/': typeof DashboardIndexRoute
  '/tasks/$taskId': typeof DashboardTasksTaskIdRouteRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRouteRoute
  '/': typeof DashboardIndexRoute
  '/tasks/$taskId': typeof DashboardTasksTaskIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/login': typeof LoginRouteRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '' | '/' | '/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/tasks/$taskId'
  id:
    | '__root__'
    | '/login'
    | '/_dashboard'
    | '/_dashboard/'
    | '/_dashboard/tasks/$taskId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LoginRouteRoute: typeof LoginRouteRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LoginRouteRoute: LoginRouteRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/login",
        "/_dashboard"
      ]
    },
    "/login": {
      "filePath": "login.route.tsx"
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/",
        "/_dashboard/tasks/$taskId"
      ]
    },
    "/_dashboard/": {
      "filePath": "_dashboard/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/tasks/$taskId": {
      "filePath": "_dashboard/tasks.$taskId.route.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
